#include <sys/types.h>

#include <stdio.h>

#include "wsite_content.h"

/*
 * First field of entry is a string which define the url path of the ressource.
 * The second one is for describing what this ressource is. Is it a html/text
 * page, a video or a image/jpeg content-type? The last one is for specifing
 * the charset of a html page as it was written (encoded) otherwise it should
 * be set to NULL. So it is NULL for image, video and any other ressource. The
 * example that follows is filled with some of http://effervecrea.net
 * ressources.
 */

struct entry entries[] = {

    {ROOT_PAGE, "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"LED-electro-nuit", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"assemblage-imprimante-3D", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"carte-conso-bar-flop", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"clignotage-arduino-nucleo-F411RE", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"courrier-tribunal-curatelle-changement", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"creation-et-bricolage-cache-prise-telephonique", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"curatelle-impayes-tribunal-changement", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"electro-retard", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"generateur-de-mot-de-passe", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"se-creer-son-gestionnaire-de-mots-de-passe", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"montage-luminaire-Dice", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"puce-sim-raccourcie", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"sortir-gros-fichiers-mobile-logiciel-gratuit", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"un-single-malt-sir", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"corruption-de-memoire-pour-le-fun-et-le-profit", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"windows-des-annees-2000-a-maintenant", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"LEDs-nuit/WP_20180316_22_08_20_Pro", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"LEDs-nuit/WP_20180305_23_47_04_Pro", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"Genie-logiciel-ou-l-energie-de-servir", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"contact", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"mentions-legales", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"creation-de-prisons", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"logiciel", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"imprim-3d", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"electronique", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"audio", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"divers", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"signal-xDSL-ou-signal-electrique-internet", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"pilotage-et-impression-rectangle-3D", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"impression_support_carte/image_1_fullscreen", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"impression-support-carte", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"impression-support-tringle-a-rideaux", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"dagopilote-pour-imprimante-discoeasy", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"dagopilote_pour_imprimante_discoeasy/image_1_fullscreen", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"diagnostic-moteurs-nissan-qashqai", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"remplacer-disque-dur-plateau-pour-SSD-sur-PC-vista", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"remplacer_disque_dur_plateau_pour_SSD_sur_PC_vista/image_1", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"remplacer_disque_dur_plateau_pour_SSD_sur_PC_vista/image_2", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"edition-et-compilation-de-code-C-avec-windows", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"apprendre-a-taper-au-clavier", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"commerce-et-achat-par-internet", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"maison-ancien-telephone-avec-nouveau-telephone", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"derouleur-vertical-de-bobine-imprimante-3d-avec-des-cales-de-bois",
     "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"mise-a-jour-firmware-marlin", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"mise-a-jour-microcode-marlin", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"reparation-etui-telephone-Honor-7A", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"psychologie-et-psychotherapie", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"en-faveur-du-langage-de-programmation-informatique-C", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"caisson-de-protection-dagoma-disco", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"algorithme-pour-diffusion-dynamique", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"futur-avec-ou-futur-sans", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"romain-landreau-3e-type", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"Akhenaton-avec-La-Face-B-dans-Metheque-et-mat", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"Akhenaton:2-titres,deux-atmospheres", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"mint-jam-saib", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"theos-spirit-EP", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"skrillex-bangarang-EP", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"formater-cle-usb-taille-invalide", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"experience-developpeur-a-distance-avec-windows", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"le-produit-cigarette-electronique-le-plus-serieux-IQOS", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"une-video-d-une-session-d-informatique", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"mise-a-jour-carte-gps-nissan", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"demo-detecteur-de-radars-avec-radarbot", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"comparaison-impression-3d-sur-scotch-et-sur-buildtak", "text/html",
     "fr-FR", "; charset=ISO-8859-1"},
    {"le-sort-de-l-electron", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"decrire-ce-que-l-on-aurait-voulu", "text/html", "fr-FR", "; charset=ISO-8859-15"},
    {"app-gcode-visiere-carreaux", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"le-rap-c-est-mal-c-est-bien", "text/html", "fr-FR", "; charset=UTF-8"},
    {"B2OBA-5G", "text/html", "fr-FR", "; charset=UTF-8"},
    {"RGPD_Ok", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"RGPD_Refus", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"CNIL", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"impression-3d-visiere", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"coup-de-pouce-pour-etai-fr", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"pilotage-imprimante-neva", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"impression-quatre-supports-cartes-3d", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"gestion-d-exception-en-C", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"impression-3d-composteur", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"app-generant-gcode", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"developpeur-logiciel-et-liberte", "text/html", "fr-FR",
     "; charset=UTF-8"},
    {"cas-ou-scenarios-d-utilisations-possibles-et-intro-(stockrecup.net)",
     "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"informatique-pro-pas-cher-et-lenovo-x200", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"les-proverbes-favoris-d-effervecreanet", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"mise-en-valeur-logiciel-et-logiciel", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"presentation-imprimante-3d-resine", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"impression-resine-porte-clef-3d-personnalise", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"installation-intelligente-temoins-reseaux", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"user-story-pour-smartphone-samsung-A22", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"astuce-optimisation-SEO-code-source-et-video", "text/html", "fr-FR",
     "; charset=ISO-8859-1"},
    {"L-amoureux-unique", "text/html", "fr-FR", "; charset=ISO-8859-1"},
    {"EnglishPages", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"password-generator", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"assembly-Dice-light-lamp", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"capture-capacitor-discharges", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"print-3d-support-card", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"dagopilot-for-3d-printer-discoeasy", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"misc", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"print_3d_support_card/image_1_fullscreen", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"wirelessly-get-large-file-out-of-smartphone-with-FreeBSD", "text/html",
     "en-US", "; charset=ISO-8859-1"},
    {"wirelessly-get-large-file-out-of-smartphone", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"contact-en", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"software", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"3d-print", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"electronic", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"home-new-handset-phone-with-old-base-phone", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"marlin-firmware-upgrade", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"xDSL-signal-or-internet-electrical-signal", "text/html", "en-US",
     "; charset=ISO-8859-1"},
    {"app-generating-gcode", "text/html", "en-US", "; charset=ISO-8859-1"},
    {"app-gcode-monobloc-visor-with-or-without-glass", "text/html", "en-US",
     "; charset=ISO-8859-1"},

    /* Desktop background image */
    {"images/EFFERVECREANET_BACKGROUND_MENU_PAGES.png", "image/png", NULL, NULL},
    {"images/BACKGROUND_EFFERVECREANET_CONTENT_PAGES.png", "image/png", NULL, NULL},

    /* Mobile background image */
    {"images/mWP_20180522_21_35_34_Pro.png", "image/png", NULL, NULL},

	  /* Menu item french */
    {"images/MENU_ITEM_EFFERVECREANET_LOGICIEL.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_LOGICIEL_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_IMPRIM3D.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_IMPRIM3D_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_ELECTRONIQUE.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_ELECTRONIQUE_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_AUDIO.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_AUDIO_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_DIVERS.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_DIVERS_FOCUS.png", "image/png", NULL, NULL},

	  /* Menu item english */
    {"images/MENU_ITEM_EFFERVECREANET_SOFTWARE.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_SOFTWARE_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_3DPRINT.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_3DPRINT_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_ELECTRONIC.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_ELECTRONIC_FOCUS.png", "image/png", NULL, NULL},

    {"images/MENU_ITEM_EFFERVECREANET_MISC.png", "image/png", NULL, NULL},
    {"images/MENU_ITEM_EFFERVECREANET_MISC_FOCUS.png", "image/png", NULL, NULL},

    /* LI item background */
    {"images/EFFERVECREANET_LI_BACKGROUND.png", "image/png", NULL, NULL},

    {"images/bg_cat.png", "image/png", NULL, NULL},
    {"images/effervecreanet_title.png", "image/png", NULL, NULL},

    {"images/Capture_dagopilote_en_1.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_edition_de_code_C_win_2.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190317_13_32_30_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_edition_de_code_C_win_1.JPG", "image/jpeg", NULL, NULL},
    {"images/WP_20190317_13_30_36_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190317_09_59_37_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190316_20_12_13_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190316_16_47_49_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/dagopilote_page_1.jpg", "image/jpeg", NULL, NULL},
    {"images/dagopilote_page_2.jpg", "image/jpeg", NULL, NULL},
    {"images/dagopilote_aide.jpg", "image/jpeg", NULL, NULL},
    {"images/dagopilote_aide_fullscreen.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190306_00_38_27_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190221_11_55_35_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190221_11_55_54_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190221_11_55_57_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190221_11_22_35_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture-support-carte_1.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture-support-carte_1_fullscreen.jpg", "image/jpeg", NULL, NULL},
    {"images/MRV_20190218_07_48_04_dp_rect_creux_blog.jpg", "image/jpeg", NULL,
     NULL},
    {"images/Capture_dp_rect_creux_blog.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_dp_1.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_dp_2.JPG", "image/jpeg", NULL, NULL},
    {"images/GESTION-ID-MDP-PIANISSIMO.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20181023-065536.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20181023-065546.jpg", "image/jpeg", NULL, NULL},
    {"images/WIN_20181001_07_52_50_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180408_10_20_04_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180410_16_47_57_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180114_20_19_04_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180131_23_46_50_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180411_18_18_04_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180412_15_32_17_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180412_15_32_30_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180412_15_32_44_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180517_00_23_28_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180604_06_35_55_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180607_17_53_50_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180612_23_29_33_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180702_02_19_56_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180827_05_36_12_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180827_07_05_11_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_08_55_39_Rich.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_09_18_52_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_09_19_50_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_09_20_01_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_10_04_14_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180904_11_27_29_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_14_59_05_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_14_59_08_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_14_59_12_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_15_57_41_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_15_57_44_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_15_58_32_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_15_58_38_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_00_21_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_03_13_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_03_23_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_03_34_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_34_12_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_34_18_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_43_48_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_43_51_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_43_54_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_43_59_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_44_04_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_44_23_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_44_25_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_44_34_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_16_44_38_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_17_34_29_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180929_17_34_38_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20180930_22_13_16_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20181001_00_11_35_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20181001_00_12_48_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/carte-bar-effervecrea-1.jpg", "image/jpeg", NULL, NULL},
    {"images/carte-bar-effervecrea-2.jpg", "image/jpeg", NULL, NULL},
    {"images/carte-bar-effervecrea-3.jpg", "image/jpeg", NULL, NULL},
    {"images/coller-os-1.jpg", "image/jpeg", NULL, NULL},
    {"images/courrier-juge-1.jpg", "image/jpeg", NULL, NULL},
    {"images/gommelet-impaye-2.jpg", "image/jpeg", NULL, NULL},
    {"images/gommelet-impaye.jpg", "image/jpeg", NULL, NULL},
    {"images/representant-legal-impaye.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_pp_en_1.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_pp_en_2.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_pp_en_3.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_pp_en_4.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_pp_en_5.JPG", "image/jpeg", NULL, NULL},
    {"images/pp-os-1.jpg", "image/jpeg", NULL, NULL},
    {"images/pp-os-2.jpg", "image/jpeg", NULL, NULL},
    {"images/pp-os-3.jpg", "image/jpeg", NULL, NULL},
    {"images/quatre-decharges.jpg", "image/jpeg", NULL, NULL},
    {"images/schema-theorique-1.jpg", "image/jpeg", NULL, NULL},
    {"images/xclip-os-1.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_wifiupload_tab.png", "image/png", NULL, NULL},
    {"images/clignotage-relais-cond-1.png", "image/png", NULL, NULL},
    {"images/clignotage-relais-cond-2.png", "image/png", NULL, NULL},
    {"images/effervecrea-wifiupload-1.png", "image/png", NULL, NULL},
    {"images/wifiupload_app_accueil.png", "image/png", NULL, NULL},
    {"images/wifiupload_app_transfert_termine.png", "image/png", NULL, NULL},
    {"images/wifiupload_ios_1.png", "image/png", NULL, NULL},
    {"images/wifiupload_ios_2.png", "image/png", NULL, NULL},
    {"images/LEDs_nuit/WP_20180305_23_47_04_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180316_22_08_20_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180316_22_08_34_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180317_01_42_27_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180317_01_42_40_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180317_01_43_01_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180317_01_43_08_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180410_23_03_03_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180410_23_03_06_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180410_23_03_11_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180410_23_03_20_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/LEDs_nuit/WP_20180316_22_08_20_ProTek/TEK0003.JPG", "image/jpeg",
     NULL, NULL},
    {"images/LEDs_nuit/WP_20180316_22_08_20_ProTek/TEK0004.JPG", "image/jpeg",
     NULL, NULL},
    {"images/LEDs_nuit/WP_20180316_22_08_20_ProTek/TEK0005.JPG", "image/jpeg",
     NULL, NULL},
    {"images/Capture_wifiupload_3.PNG", "image/png", NULL, NULL},
    {"images/WP_20190113_22_46_54_Rich.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20190113_22_46_28_Rich.jpg", "image/jpeg", NULL, NULL},
    {"images/sign_efrvnet.jpg", "image/jpeg", NULL, NULL},
    {"images/ss_dagopilote.JPG", "image/jpeg", NULL, NULL},
    {"images/WP_20190208_02_10_19_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/dagopilote_disco_1.png", "image/png", NULL, NULL},
    {"images/Capture_dvorak7min_1.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_dvorak7min_2.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_dvorak7min_3.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190328_004612.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190328_004449.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190328_004310.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190327_195335.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190327_195506.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190327_195516.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190401_161452.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190401_161519.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190512_133207.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190512_133233.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190513_184402.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190513_184849.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190513_185128.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190513_185511.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190513_191843.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190526_164351.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190729_001917.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190729_143726.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190730_211656.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190730_212421.jpg", "image/jpeg", NULL, NULL},

    {"images/IMG_20190402_120148.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_195800.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_215529.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_220652.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_220654.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_231353.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190404_231400.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20190405_073845.jpg", "image/jpeg", NULL, NULL},

    {"images/xDSL/TEK0000.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0001.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0002.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0003.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0004.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0005.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0006.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0007.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0008.JPG", "image/jpeg", NULL, NULL},
    {"images/xDSL/TEK0009.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_marlin_cur.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_marlin_cur2.JPG", "image/jpeg", NULL, NULL},
    {"images/Capture_wifiupload2_en_1.jpg", "image/jpeg", NULL, NULL},
    {"images/Capture_wifiupload2_en_2.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20190612-171336.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20190612-171426.jpg", "image/jpeg", NULL, NULL},
    {"images/wu-freebsd-screenshot-1.jpg", "image/jpeg", NULL, NULL},
    {"images/wu-freebsd-screenshot-2.jpg", "image/jpeg", NULL, NULL},
    {"images/wu-en-freebsd-screenshot-1.jpg", "image/jpeg", NULL, NULL},
    {"images/wu-en-freebsd-screenshot-2.jpg", "image/jpeg", NULL, NULL},
    {"images/3e_type.JPG", "image/jpeg", NULL, NULL},
    {"images/mint_jam_saib.JPG", "image/jpeg", NULL, NULL},
    {"images/theos.JPG", "image/jpeg", NULL, NULL},
    {"images/la-face-B-et-la-cosca-par-akh-dans-metheque-et-mat.png", "image/png", NULL, NULL},

    {"images/IMG_20191124_023040.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20191124_025746.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20191124_030059.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20191124_025444.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20191124_025838.jpg", "image/jpeg", NULL, NULL},

    {"images/IQOS.png", "image/png", NULL, NULL},
    {"images/skrillex.JPG", "image/png", NULL, NULL},

    {"images/IMG_20200226_080617.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200226_080749.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200226_080808.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200226_082658.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200226_082700.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200224-021118.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200224-021124.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200224-021130.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200224-021135.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200224-021140.jpg", "image/jpeg", NULL, NULL},

    {"images/Screenshot_20200406-211115.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200406-211235.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200406-211313.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20200406-211322.jpg", "image/jpeg", NULL, NULL},

    {"images/IMG_IMP3D_3M_BUILDTAK.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200502_053857_croped.png", "image/jpeg", NULL, NULL},
    {"images/IMG_20200502_054045_croped.png", "image/jpeg", NULL, NULL},
    {"images/IMG_20200502_082906_croped.png", "image/jpeg", NULL, NULL},
    {"images/IMG_20200506_165438.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200506_165518.jpg", "image/jpeg", NULL, NULL},

    {"images/IMG_20200628_065912.jpg", "image/jpeg", NULL, NULL},
    {"images/IMG_20200709_070252.jpg", "image/jpeg", NULL, NULL},

    {"images/SCAN0000.JPG", "image/jpeg", NULL, NULL},
    {"images/SCAN0002.JPG", "image/jpeg", NULL, NULL},

    {"images/WP_20210503_06_40_15_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20210503_06_38_56_Pro.jpg", "image/jpeg", NULL, NULL},
    {"images/WP_20210503_06_38_30_Pro.jpg", "image/jpeg", NULL, NULL},

    {"images/algorecup.png", "image/png", NULL, NULL},

    {"images/logo_3.jpg", "image/jpeg", NULL, NULL},
    {"images/logo4_effervecreanet.png", "image/png", NULL, NULL},

    {"images/pub3.png", "image/png", NULL, NULL},

    {"images/composteur_large_project_image.jpg", "image/jpeg", NULL, NULL},
    {"images/composteur_medium_project_step_image.png", "image/png", NULL,
     NULL},
    {"images/composteur_translucide_dimension_image_vue_cote.jpg", "image/jpeg",
     NULL, NULL},
    {"images/composteur_translucide_dimension_image_vue_dessus.jpg",
     "image/jpeg", NULL, NULL},

    {"images/AppGenerantGcodeCapture1.PNG", "image/png", NULL, NULL},
    {"images/AppGenerantGcodeCapture1_en.PNG", "image/png", NULL, NULL},
    {"images/AppGenerantGcodeCapture2.PNG", "image/png", NULL, NULL},
    {"images/AppGenerantGcodeCapture2_en.PNG", "image/png", NULL, NULL},

    {"images/IMG_20210826_163511_1.jpg", "image/jpg", NULL, NULL},
    {"images/IMG_20210826_163607_1.jpg", "image/jpg", NULL, NULL},
    {"images/IMG_20210826_163654_1.jpg", "image/jpg", NULL, NULL},

    {"images/clanche_fenetre_1.png", "image/png", NULL, NULL},
    {"images/IMG_20210903_002903_1.jpg", "image/jpg", NULL, NULL},
    {"images/cylindre_perce.png", "image/png", NULL, NULL},
    {"images/clanche_reparee.png", "image/png", NULL, NULL},
    {"images/cylindre_imprime.png", "image/png", NULL, NULL},

    {"images/en-wifiupload-1.png", "image/png", NULL, NULL},
    {"images/en-wifiupload-2.png", "image/png", NULL, NULL},
    {"images/en-wifiupload-3.png", "image/png", NULL, NULL},
    {"images/en-wifiupload-4.png", "image/png", NULL, NULL},
    {"images/en-wifiupload-5.png", "image/png", NULL, NULL},
    {"images/en-wifiupload-6.png", "image/png", NULL, NULL},

    {"images/smart-switch-install.jpg", "image/jpg", NULL, NULL},
    {"images/AdobeStock_422501896_effervecreanet_wifiupload.png", "image/png",
     NULL, NULL},
    {"images/VISIERE-AVEC-TROUS-TRANSLUCIDE.jpg", "image/jpg", NULL, NULL},
    {"images/IMG-VISIERE-TROUS-BLANCHE.jpg", "image/jpg", NULL, NULL},
    {"images/VISIERE-BLANCHE-AVEC-PLEXI.jpg", "image/jpg", NULL, NULL},

    {"images/AdobeStock_119738231_converted.png", "image/png", NULL, NULL},
    {"images/AdobeStock_46342961.jpeg", "image/jpg", NULL, NULL},
    {"images/AdobeStock_330958256_converted.png", "image/png", NULL, NULL},

    {"images/porte-clef-5.png", "image/png", NULL, NULL},
    {"images/IMG_20220316_172809.png", "image/png", NULL, NULL},
    {"images/IMG_20220316_173134.png", "image/png", NULL, NULL},
    {"images/IMG_20220316_173417.png", "image/png", NULL, NULL},
    {"images/IMG_20220316_173541.png", "image/png", NULL, NULL},
    {"images/IMG_20220316_174228.png", "image/png", NULL, NULL},
    {"images/AdobeStock_322622703_modified.jpg", "image/jpeg", NULL, NULL},
    {"images/Screenshot_20220603-054026_OneUIHome.jpg", "image/jpeg", NULL, NULL},
    {"images/vu_a_la_tele_google.png", "image/png", NULL, NULL},
    {"images/crypto_lock_illu_effervecrea.png", "image/png", NULL, NULL},
    {"images/ASTUCE_SEO_FRANCKSYS.png", "image/png", NULL, NULL},
    {"images/2022-07-01-BROWSERSTACK-WITH-STOCKRECUPNET-WINXP-800x600.png", "image/png", NULL, NULL},
    {"images/POSTER-ASTUCE-SEO-VIDEO-STOCKRECUPNET.png", "image/png", NULL, NULL},
    {"images/BOOBA-TEMPS-MORT-45-SCIENTIFIC.png", "image/png", NULL, NULL},

    {"videos/wifiupload-apple-ios.mp4", "video/mp4", NULL, NULL},
    {"videos/sgfm-linux-1.mp4", "video/mp4", NULL, NULL},
    {"videos/sgfm-linux-2.mp4", "video/mp4", NULL, NULL},
    {"videos/se-creer-son-gmdp.mp4", "video/mp4", NULL, NULL},
    {"videos/ARDUINO-NUCLEO-F411RE-BLINKS.mp4", "video/mp4", NULL, NULL},
    {"videos/blink_7seg_2led__Medium.mp4", "video/mp4", NULL, NULL},
    /* {"videos/wu-fr-FreeBSD-X11.mp4", "video/mp4", NULL, NULL}, */
    {"videos/expdistwin.mp4", "video/mp4", NULL, NULL},
    {"videos/informatique-session-7.mp4", "video/mp4", NULL, NULL},
    {"videos/VID_20200226_081419.mp4", "video/mp4", NULL, NULL},
    {"videos/demo-radarbot.mp4", "video/mp4", NULL, NULL},
    {"videos/pilotage-neva-dagoma.mp4", "video/mp4", NULL, NULL},
    {"videos/imprim-3d-transit-2-piece.mp4", "video/mp4", NULL, NULL},
    {"videos/WP_20201120_18_30_40_Pro.mp4", "video/mp4", NULL, NULL},
    {"videos/VID_20210826_163729.mp4", "video/mp4", NULL, NULL},
    {"videos/VIDEO-VISIERE-DEPOSE-CARREAUX-ET-CLIPS.mp4", "video/mp4", NULL, NULL},
    {"videos/ASTUCE_SEO_FRANCKSYS.mp4", "video/mp4", NULL, NULL},
    {"videos/ASTUCE2-SEO-FRANCKSYS.mp4", "video/mp4", NULL, NULL},
    {"videos/FRANCK-SEO-ASTUCE-VIDEO3.mp4", "video/mp4", NULL, NULL},

    {"robots.txt", "text/plain", NULL, NULL},
    {"favicon.ico", "image/png", NULL, NULL},
    {"BingSiteAuth.xml", "text/xml", NULL, NULL},
    {"google022a2661792301c1.html", "text/html", NULL, NULL},

    {"exec/pp.exe", "application/octet-stream", NULL, NULL},
    {"exec/pp.zip", "application/octet-stream", NULL, NULL},
    {"exec/pp_en.exe", "application/octet-stream", NULL, NULL},
    {"exec/wifiupload-4.19-win64-installer.msi", "application/octet-stream",
     NULL, NULL},
    {"exec/wifiupload-4.19-win64-installer.msi.sha256",
     "application/octet-stream", NULL, NULL},
    {"exec/wifiupload-fr-4.21-win64-installer.msi", "application/octet-stream",
     NULL, NULL},
    {"exec/wifiupload-fr-4.21-win64-installer.msi.sha256",
     "application/octet-stream", NULL, NULL},
    {"exec/wifiupload-en-4.21-win64-installer.msi", "application/octet-stream",
     NULL, NULL},
    {"exec/wifiupload-en-4.21-win64-installer.msi.sha256",
     "application/octet-stream", NULL, NULL},
    {"exec/wifiupload4.msi", "application/octet-stream", NULL, NULL},
    {"exec/wifiupload3.msi", "application/octet-stream", NULL, NULL},
    {"exec/wifiupload2.exe", "application/octet-stream", NULL, NULL},
    {"exec/wifiupload_en.msi", "application/octet-stream", NULL, NULL},
    {"exec/rect_creux.exe", "application/octet-stream", NULL, NULL},
    {"exec/Composteur_dagoma0_g.exe", "application/octet-stream", NULL, NULL},
    {"exec/GarbageCollector_dagoma0_g.exe", "application/octet-stream", NULL,
     NULL},
    {"exec/VisiereSansCarreaux_dagoma0_g.exe", "application/octet-stream", NULL, NULL},
    {"exec/VisiereAvecCarreaux_dagoma0_g.exe", "application/octet-stream", NULL, NULL},
    {"exec/VisorWithoutGlass_dagoma0_g.exe", "application/octet-stream", NULL, NULL},
    {"exec/VisorWithGlass_dagoma0_g.exe", "application/octet-stream", NULL, NULL},
    {"exec/CalibrerMagis.exe", "application/octet-stream", NULL, NULL},
    {"exec/CalibrateMagis.exe", "application/octet-stream", NULL, NULL},
    {"exec/Imprimer_dagoma0_g.exe", "application/octet-stream", NULL, NULL},

    {"source/pp.c", "application/octet-stream", NULL, NULL},
    {"source/rect_creux.c", "application/octet-stream", NULL, NULL},
    {"source/rect_creux.g", "application/octet-stream", NULL, NULL},
    {"source/rect_creux.txt", "text/plain", NULL, NULL},
    {"source/support_carte.c", "application/octet-stream", NULL, NULL},
    {"source/support_carte.g", "application/octet-stream", NULL, NULL},
    /* {"source/wifiupload-fr-FreeBSD-X11.tar.gz", "application/octet-stream",
     NULL, NULL}, */
    /* {"source/wifiupload-en-FreeBSD-X11.tar.gz", "application/octet-stream", 
     NULL, NULL}, */
    {"source/dagodriver_bsd.tar.gz", "application/octet-stream", NULL, NULL},
    {"source/mu-0.8.tar.gz", "application/octet-stream", NULL, NULL},
    {"source/3d_objects_source.zip", "application/octet-stream", NULL, NULL},

    /*
    {"pdf/plaquette_presentation_commerciale_stockrecup.pdf", "application/pdf",
     NULL, NULL},
    {"pdf/stockrecup_brand_marketing_screen.pdf", "application/pdf", NULL,
     NULL},
    */

    {"sitemap_2022_07_24.xml", "application/xml", NULL, NULL},

    {"", "", NULL, NULL},
};
